apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  labels:
    app: mlflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow:v1
        env:
        - name: FILE_STORE
          valueFrom:
            secretKeyRef:
              name: backend-store-secret
              key: connection-string
        # https://www.mlflow.org/docs/latest/tracking.html#backend-stores
        - name: ARTIFACT_STORE
          value: gs://mlflow-artifact-store/artifacts
        ports:
        - containerPort: 5000
